AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  visa
  Sample SAM Template for visa

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Resources:
  VisaPredictionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: visa/
      Handler: app.lambda_handler
      Runtime: python3.6
      Timeout: 2
      Events:
        Predict:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /predict
            Method: get 

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisaPredictionApi:
    Description: "API Gateway endpoint URL for Prod stage for predict function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  VisaPredictionFunction:
    Description: "Visa Waiting Time Prediction Lambda Function ARN"
    Value: !GetAtt VisaPredictionFunction.Arn
    #  VisaPredictionIamRole:
    #Description: "Implicit IAM Role created for Visa Waiting Time Predicting function"
    #Value: !GetAtt VisaPredictionIamRole.Arn
